package com.francetelecom.wsa.wsdl.buconfiguration.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-01-08T10:07:45.338Z
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "BuConfigurationService",
                  wsdlLocation = "file:/Users/eyoboue/AnypointStudio/workspace/booster-connector-acs/src/src/main/resources/wsdl/karma/ws_activation.wsdl",
                  targetNamespace = "http://WSA.francetelecom.com./wsdl/BuConfiguration/v1")
public class BuConfigurationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://WSA.francetelecom.com./wsdl/BuConfiguration/v1", "BuConfigurationService");
    public final static QName BuConfigurationV1 = new QName("http://WSA.francetelecom.com./wsdl/BuConfiguration/v1", "BuConfiguration_v1");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/eyoboue/AnypointStudio/workspace/booster-connector-acs/src/src/main/resources/wsdl/karma/ws_activation.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BuConfigurationService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/eyoboue/AnypointStudio/workspace/booster-connector-acs/src/src/main/resources/wsdl/karma/ws_activation.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BuConfigurationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BuConfigurationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BuConfigurationService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BuConfigurationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BuConfigurationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BuConfigurationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BuConfiguration
     */
    @WebEndpoint(name = "BuConfiguration_v1")
    public BuConfiguration getBuConfigurationV1() {
        return super.getPort(BuConfigurationV1, BuConfiguration.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BuConfiguration
     */
    @WebEndpoint(name = "BuConfiguration_v1")
    public BuConfiguration getBuConfigurationV1(WebServiceFeature... features) {
        return super.getPort(BuConfigurationV1, BuConfiguration.class, features);
    }

}
